# Generated by Django 4.1 on 2022-08-27 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
