# Generated by Django 4.1 on 2022-09-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_product_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=150, verbose_name='Rut')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('direction', models.TextField(max_length=500, verbose_name='Dirección')),
                ('number', models.IntegerField(verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['id'],
            },
        ),
    ]
