# Generated by Django 4.1 on 2022-09-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='foto',
            field=models.ImageField(default=1, upload_to='media', verbose_name='Imagen del producto'),
            preserve_default=False,
        ),
    ]
