# Generated by Django 4.1 on 2022-09-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quanty',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
            preserve_default=False,
        ),
    ]
