# Generated by Django 4.1 on 2022-09-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_quanty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre Empleado')),
                ('apellido', models.TextField(max_length=500, verbose_name='Apellido')),
                ('cedula', models.IntegerField(verbose_name='N° de documento')),
                ('horaen', models.CharField(max_length=7, verbose_name='Hora entrada')),
                ('horasal', models.CharField(max_length=7, verbose_name='Hora Salida')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horario',
                'ordering': ['id'],
            },
        ),
    ]
