# Generated by Django 4.1 on 2022-09-26 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_citas_hora_alter_citas_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citas',
            options={'ordering': ['id'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelTable(
            name='citas',
            table='cita',
        ),
    ]
