# Generated by Django 4.1 on 2022-09-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_alter_citas_options_alter_citas_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='hora',
            field=models.CharField(max_length=10, verbose_name='Hora'),
        ),
    ]
