# Generated by Django 4.1 on 2022-10-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='foto',
            field=models.ImageField(default=1, upload_to='media', verbose_name='Foto'),
            preserve_default=False,
        ),
    ]
