# Generated by Django 4.1 on 2022-10-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_servicio_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='media', verbose_name='Foto')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('disponibilidad', models.CharField(max_length=10, verbose_name='Disponivilidad')),
                ('servicio', models.ManyToManyField(to='libreria.servicio', verbose_name='Servicio')),
            ],
        ),
    ]
