# Generated by Django 4.1 on 2022-10-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0010_remove_empleado_servicio_empleado_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='disponibilidad',
            field=models.CharField(max_length=15, verbose_name='Disponivilidad'),
        ),
    ]
