# Generated by Django 4.1 on 2022-10-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0011_alter_empleado_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='disponibilidad',
            field=models.CharField(max_length=18, verbose_name='Disponivilidad'),
        ),
    ]
