# Generated by Django 4.1 on 2022-10-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0012_alter_empleado_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='jornadada',
            field=models.CharField(default=1, max_length=18, verbose_name='Jornada'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='servicio',
        ),
        migrations.AddField(
            model_name='empleado',
            name='servicio',
            field=models.ManyToManyField(to='libreria.dia', verbose_name='Servicio'),
        ),
    ]
