# Generated by Django 4.1 on 2022-10-01 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0013_empleado_jornadada_remove_empleado_servicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='disponibilidad',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='servicio',
        ),
        migrations.AddField(
            model_name='empleado',
            name='disponibilidad',
            field=models.ManyToManyField(to='libreria.dia', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreria.servicio', verbose_name='Servicio'),
            preserve_default=False,
        ),
    ]
