# Generated by Django 4.1 on 2022-10-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0014_remove_empleado_disponibilidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='jornadada',
            new_name='jornanada',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='disponibilidad',
            field=models.ManyToManyField(to='libreria.dia', verbose_name='Disponibilidad'),
        ),
    ]
