# Generated by Django 4.1 on 2022-10-01 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0015_rename_jornadada_empleado_jornanada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='jornanada',
            new_name='jornada',
        ),
    ]
