# Generated by Django 4.1 on 2022-10-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0016_rename_jornanada_empleado_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
