# Generated by Django 4.1 on 2022-10-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0017_alter_servicio_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='disponibilidad',
        ),
        migrations.AddField(
            model_name='empleado',
            name='disponibilidad',
            field=models.CharField(default=1, max_length=150, verbose_name='Disponivilidad'),
            preserve_default=False,
        ),
    ]
