# Generated by Django 4.1 on 2022-10-01 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0018_remove_empleado_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='estilista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreria.empleado', verbose_name='Estilista'),
            preserve_default=False,
        ),
    ]
