# Generated by Django 4.1 on 2022-10-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0019_citas_estilista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='estilista',
            field=models.CharField(max_length=70, verbose_name='Estilista'),
        ),
    ]
