# Generated by Django 4.1 on 2022-10-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0020_alter_citas_estilista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
